### PR TITLE
put to_xml and from_xml on the OME class

### PR DESCRIPTION
**Pull request by tlambert03**
modification for you to consider...  this puts most of the main functionality in the OME class namespace:

```python
from ome_types import OME

ome = OME.from_xml('path/to/ome.xml')
xml = ome.to_xml()
some_dict = ome.to_dic()
```

### CODE REVIEW

**Comment by jmuhlich** [comment]
Oh, I guess this got auto-closed when I merged the PR or deleted its branch after? Sorry. Anyway, I'm actually against this change. I think the model class API should stick to representing the model itself, not XML parsing/generation or anything else. I've used (and written!) APIs that add I/O to model classes, and it always just gets messy.

**Comment by tlambert03** [comment]
I agree with you for pretty much all of the model, and I wouldn't want this pattern to proliferate to the inner nodes...  the `OME` class just seems a little special and has the potential to be the one main export from this library.  Not gonna die on that hill though... but i do think that if we don't do this we should start cleaning up the organization of the main library exports.

**Comment by jmuhlich** [comment]
The simplest and probably most common use case is parsing XML into an OME object and trawling through the fields for whatever the user needs, i.e. read-only. For this, the user actually only needs to import `from_xml`, not even `OME`. I 100% agree we should clean up the exports and module organization!

**Comment by jmuhlich** [comment]
Sorry I should clarify a little better: If the goal is to simplify the requirements for the user, I was pointing out that the most common use case already has a very simple interface: the `from_xml` function. More complex use cases would require importing a few more pieces, and that's fine.

**Pull request closed without merging**
